name: network_info_plus
description: Flutter plugin for discovering information (e.g. WiFi details) of the network.
version: 8.0.0
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/network_info_plus/network_info_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/network_info_plus
topics:
  - network
  - information
  - utils

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.network_info
        pluginClass: NetworkInfoPlusPlugin
      ios:
        pluginClass: FPPNetworkInfoPlusPlugin
      linux:
        dartPluginClass: NetworkInfoPlusLinuxPlugin
      macos:
        pluginClass: NetworkInfoPlusPlugin
      windows:
        dartPluginClass: NetworkInfoPlusWindowsPlugin
      web:
        pluginClass: NetworkInfoPlusWebPlugin
        fileName: src/network_info_plus_web.dart

dependencies:
  collection: ^1.19.1
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.17.0
  network_info_plus_platform_interface: ^3.0.0
  nm: ^0.5.0
  win32: ^6.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  plugin_platform_interface: ^2.1.8
