name: Feature request
description: Suggest a new idea for one of plugins.
title: "[Request]: "
labels: [ "enhancement", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using this plugin!

        If you are looking for support, please check out our documentation
        or consider asking a question on Stack Overflow:
        * https://plus.fluttercommunity.dev/docs/overview

        If you would like to see a new feature or if our documentation doesn't have an answer
        to what you're looking for, then fill our the other template.
  - type: input
    id: plugin
    attributes:
      label: Plugin
      description: Plugin name
      placeholder: ex. share_plus
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.

        Describe alternative solutions you've considered. Is there another package
        on pub.dev/flutter that already solves this?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like the plugin to be able to do.

        Consider attaching images showing what you are imagining.
    validations:
      required: true
