#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/majid/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/majid/Projects/FlutterCommunity/package_transfer_guide/src/connectivity_plus/connectivity_for_web"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/majid/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.3.1"
export "FLUTTER_BUILD_NUMBER=2"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
