module.exports = [
  {
    name: 'Battery ➕',
    pub: 'battery_plus',
    support: {
      web: true,
      android: true,
      ios: true,
      macos: true,
      linux: true,
      windows: true,
    },
    maintainer: {
      web: 'mhadaily',
      android: '',
      ios: '',
      macos: '',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Connectivity ➕',
    pub: 'connectivity_plus',
    support: {
      web: true,
      android: true,
      ios: true,
      macos: true,
      linux: true,
      windows: true,
    },
    maintainer: {
      web: 'mhadaily',
      android: '',
      ios: '',
      macos: '',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Device Info ➕',
    pub: 'device_info_plus',
    support: {
      web: true,
      android: true,
      ios: true,
      macos: true,
      linux: true,
      windows: false,
    },
    maintainer: {
      web: 'mhadaily',
      android: '',
      ios: '',
      macos: '',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Network Info ➕',
    pub: 'network_info_plus',
    support: {
      web: false,
      android: true,
      ios: true,
      macos: true,
      linux: true,
      windows: true,
    },
    maintainer: {
      web: 'mhadaily',
      android: '',
      ios: '',
      macos: '',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Package Info ➕',
    pub: 'package_info_plus',
    support: {
      android: true,
      ios: true,
      macos: true,
      web: true,
      linux: true,
      windows: true,
    },
    maintainer: {
      android: '',
      ios: '',
      macos: '',
      web: 'mhadaily',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Sensor ➕',
    pub: 'sensors_plus',
    support: {
      web: true,
      android: true,
      ios: true,
      macos: false,
      linux: false,
      windows: false,
    },
    maintainer: {
      web: 'mhadaily',
      android: '',
      ios: '',
      macos: '',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Share ➕',
    pub: 'share_plus',
    support: {
      web: true,
      android: true,
      ios: true,
      macos: true,
      linux: true,
      windows: true,
    },
    maintainer: {
      web: 'mhadaily',
      android: 'miquelbeltran',
      ios: 'miquelbeltran',
      macos: '',
      linux: 'jpnurmi',
      windows: 'slightfoot',
    },
  },
  {
    name: 'Android Alarm Manager ➕',
    pub: 'android_alarm_manager_plus',
    support: {
      android: true,
    },
    maintainer: {
      android: 'miquelbeltran',
    },
  },
  {
    name: 'Android Intent ➕',
    pub: 'android_intent_plus',
    support: {
      android: true,
    },
    maintainer: {
      android: 'miquelbeltran',
    },
  },
];
